USE LUXI_FASHON;

DELIMITER //
CREATE PROCEDURE ELIMINAR_PRODUCTO_T(IN ID INT)
BEGIN
DELETE FROM Producto_terminado WHERE id_producto_t = ID;
END;
//

CREATE PROCEDURE ELIMINAR_ROL(IN ID INT)
BEGIN
    DELETE FROM Rol WHERE id_rol = ID;
END;
//


CREATE PROCEDURE ELIMINAR_EMPLEADO(IN ID INT)
BEGIN
    DELETE FROM Empleado WHERE id_empleado = ID;
END;
//


CREATE PROCEDURE ELIMINAR_CLIENTE(IN ID INT)
BEGIN
    DELETE FROM Cliente WHERE id_cliente = ID;
END;
//


CREATE PROCEDURE ELIMINAR_FACTURA_VENTA(IN ID INT)
BEGIN
    DELETE FROM Factura_Venta WHERE cod_factura_v = ID;
END;
//


CREATE PROCEDURE ELIMINAR_PEDIDO(IN ID INT)
BEGIN
    DELETE FROM Pedido WHERE id_pedido = ID;
END;
//


CREATE PROCEDURE ELIMINAR_PRODUCCION(IN ID INT)
BEGIN
    DELETE FROM Produccion WHERE id_produccion = ID;
END;
//


CREATE PROCEDURE ELIMINAR_PRODUCTO_TERMINADO(IN ID INT)
BEGIN
    DELETE FROM Producto_terminado WHERE id_producto_t = ID;
END;
//


CREATE PROCEDURE ELIMINAR_DETALLE_FACTURAV_PRODUTOT(IN ID INT)
BEGIN
    DELETE FROM detalle_facturav_produtot WHERE id_dettallef_p = ID;
END;
//


CREATE PROCEDURE ELIMINAR_MATERIA_PRIMA(IN ID INT)
BEGIN
    DELETE FROM Materia_prima WHERE id_materia_p = ID;
END;
//


CREATE PROCEDURE ELIMINAR_FACTURA_COMPRA(IN ID INT)
BEGIN
    DELETE FROM Factura_compra WHERE cod_factura_compra = ID;
END;
//


CREATE PROCEDURE ELIMINAR_DETALLE_FACTUC_COMPRA_M(IN ID INT)
BEGIN
    DELETE FROM Detalle_factuc_compra_m WHERE id_detalle_fcm = ID;
END;
//


CREATE PROCEDURE ELIMINAR_DETALLE_PRODUCCION_MATERIAP(IN ID INT)
BEGIN
    DELETE FROM Detalle_produccion_materiap_ WHERE id_dettalle_produccion_materiap = ID;
END;
//

DELIMITER ;
