# Generated by Django 4.2 on 2026-04-24 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estampado',
            fields=[
                ('id_estamp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estamp', models.CharField(max_length=100)),
                ('imagen_estamp', models.ImageField(blank=True, null=True, upload_to='estampados/')),
                ('imagen_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('costo_adi', models.DecimalField(decimal_places=3, max_digits=12)),
                ('tipo_estamp', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_provee', models.AutoField(primary_key=True, serialize=False)),
                ('nom_provee', models.CharField(max_length=100)),
                ('fech_ingre', models.DateField()),
                ('num_tel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento_matp',
            fields=[
                ('id_mmtp', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mmtp', models.CharField(max_length=100)),
                ('mat_mmtp', models.CharField(max_length=100)),
                ('fecha_mmtp', models.DateField()),
                ('color_mmtp', models.CharField(max_length=100)),
                ('stock_mmtp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_proveedor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMovimiento_matp',
            fields=[
                ('id_mmtp', models.IntegerField(blank=True, db_index=True)),
                ('tipo_mmtp', models.CharField(max_length=100)),
                ('mat_mmtp', models.CharField(max_length=100)),
                ('fecha_mmtp', models.DateField()),
                ('color_mmtp', models.CharField(max_length=100)),
                ('stock_mmtp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_proveedor_fk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'historical movimiento_matp',
                'verbose_name_plural': 'historical movimiento_matps',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
