# Generated by Django 4.2 on 2026-04-24 00:24

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estampado',
            fields=[
                ('id_estamp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estamp', models.CharField(max_length=100)),
                ('imagen_estamp', models.ImageField(blank=True, null=True, upload_to='estampados/')),
                ('imagen_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('costo_adi', models.DecimalField(decimal_places=3, max_digits=12)),
                ('tipo_estamp', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMovimiento_matp',
            fields=[
                ('id_mmtp', models.IntegerField(blank=True, db_index=True)),
                ('tipo_mmtp', models.CharField(max_length=100)),
                ('mat_mmtp', models.CharField(max_length=100)),
                ('fecha_mmtp', models.DateField()),
                ('color_mmtp', models.CharField(max_length=100)),
                ('stock_mmtp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical movimiento_matp',
                'verbose_name_plural': 'historical movimiento_matps',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Movimiento_matp',
            fields=[
                ('id_mmtp', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mmtp', models.CharField(max_length=100)),
                ('mat_mmtp', models.CharField(max_length=100)),
                ('fecha_mmtp', models.DateField()),
                ('color_mmtp', models.CharField(max_length=100)),
                ('stock_mmtp', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_provee', models.AutoField(primary_key=True, serialize=False)),
                ('nom_provee', models.CharField(max_length=100)),
                ('fech_ingre', models.DateField()),
                ('num_tel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_hex', models.CharField(default='#ffffff', max_length=7)),
                ('tipo_personalizacion', models.CharField(max_length=20)),
                ('foto_frente', models.ImageField(blank=True, null=True, upload_to='renders_3d/')),
                ('foto_espalda', models.ImageField(blank=True, null=True, upload_to='renders_3d/')),
                ('foto_lateral', models.ImageField(blank=True, null=True, upload_to='renders_3d/')),
                ('precio_final', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estampado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.estampado')),
            ],
        ),
    ]
