# Generated by Django 4.2 on 2026-04-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento_matp',
            name='talla_mmtp',
        ),
    ]
