# Generated by Django 6.0.4 on 2026-06-08 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovimiento_matp',
            name='pedido_origen',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.pedido'),
        ),
        migrations.AddField(
            model_name='movimiento_matp',
            name='pedido_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.pedido'),
        ),
        migrations.AddField(
            model_name='pedidopersonalizado',
            name='estampado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.estampado'),
        ),
        migrations.AddField(
            model_name='pedidopersonalizado',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto'),
        ),
        migrations.AddField(
            model_name='movimiento_matp',
            name='id_proveedor_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedor'),
        ),
        migrations.AddField(
            model_name='historicalmovimiento_matp',
            name='id_proveedor_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.proveedor'),
        ),
    ]
