# Generated by Django 4.2 on 2026-03-24 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='id_prove',
            new_name='id_provee',
        ),
    ]
