# Generated by Django 4.2 on 2026-03-24 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_id_prove_proveedor_id_provee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estampado',
            old_name='id_estam',
            new_name='id_estamp',
        ),
        migrations.RenameField(
            model_name='estampado',
            old_name='link_estam',
            new_name='link_estamp',
        ),
        migrations.RenameField(
            model_name='estampado',
            old_name='nombre_estam',
            new_name='nombre_estamp',
        ),
        migrations.RenameField(
            model_name='estampado',
            old_name='tipo_estam',
            new_name='tipo_estamp',
        ),
        migrations.RenameField(
            model_name='movimiento_matp',
            old_name='color_movi_mtp',
            new_name='color_mmtp',
        ),
        migrations.RenameField(
            model_name='movimiento_matp',
            old_name='fecha_movi_mtp',
            new_name='fecha_mmtp',
        ),
        migrations.RenameField(
            model_name='movimiento_matp',
            old_name='id_estam_fk_invent',
            new_name='id_estamp_fk_invent',
        ),
        migrations.RenameField(
            model_name='movimiento_matp',
            old_name='id_movi_mtp',
            new_name='id_mmtp',
        ),
        migrations.RenameField(
            model_name='movimiento_matp',
            old_name='stock_movi_mtp',
            new_name='stock_mmtp',
        ),
        migrations.RenameField(
            model_name='movimiento_matp',
            old_name='talla_movi_mtp',
            new_name='talla_mmtp',
        ),
        migrations.RenameField(
            model_name='movimiento_matp',
            old_name='tipo_movi_mtp',
            new_name='tipo_mmtp',
        ),
    ]
