# Generated by Django 4.2 on 2026-03-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_id_estam_estampado_id_estamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estampado',
            name='link_estamp',
        ),
        migrations.AddField(
            model_name='estampado',
            name='imagen_estamp',
            field=models.ImageField(blank=True, null=True, upload_to='estampados/'),
        ),
        migrations.AddField(
            model_name='estampado',
            name='imagen_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
