# Generated by Django 6.0.3 on 2026-03-17 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Det_valor',
            fields=[
                ('id_det_valor', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_pedido', models.CharField(max_length=200)),
                ('estado_pago', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_produc', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_product', models.ImageField(max_length=500, upload_to='producto/')),
                ('imagen_hash', models.CharField(editable=False, max_length=64, null=True, unique=True)),
                ('nom_produc', models.CharField(max_length=50)),
                ('desc_produc', models.CharField(max_length=200)),
                ('categoria_produc', models.CharField(max_length=50)),
                ('estado_produc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id_abono', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_abono', models.DateField(auto_now_add=True)),
                ('monto_abono', models.BigIntegerField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('id_detvalor_fk_abono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.det_valor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ped', models.CharField(max_length=100)),
                ('talla_ped', models.CharField(max_length=50)),
                ('color_ped', models.CharField(max_length=50)),
                ('categoria_ped', models.CharField(max_length=50)),
                ('material_ped', models.CharField(max_length=100)),
                ('cant_ped', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc_ped', models.CharField(max_length=200)),
                ('fecha_ped', models.DateField(auto_now_add=True)),
                ('subtotal_ped', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_ped', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_ped', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('id_abono_fk_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.abono')),
                ('id_clien_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='det_valor',
            name='id_prod_fk_detval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto'),
        ),
        migrations.CreateModel(
            name='Variacion',
            fields=[
                ('id_var', models.AutoField(primary_key=True, serialize=False)),
                ('talla_var', models.CharField(max_length=50)),
                ('cant_soli', models.IntegerField()),
                ('color_var', models.CharField(max_length=100)),
                ('mat_var', models.CharField(max_length=200)),
                ('costo_var', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_estam_fk_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.estampado')),
            ],
        ),
        migrations.AddField(
            model_name='det_valor',
            name='id_var_fk_detval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.variacion'),
        ),
    ]
