# Generated by Django 6.0.2 on 2026-03-31 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_produc', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_product', models.ImageField(max_length=500, upload_to='producto/')),
                ('imagen_hash', models.CharField(editable=False, max_length=64, null=True, unique=True)),
                ('nom_produc', models.CharField(max_length=50)),
                ('gen_produc', models.CharField(max_length=50)),
                ('desc_produc', models.CharField(max_length=200)),
                ('categoria_produc', models.CharField(max_length=50)),
                ('estado_produc', models.CharField(max_length=50)),
                ('dias_produccion', models.PositiveIntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ped', models.DateField(auto_now_add=True)),
                ('subtotal_ped', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_ped', models.DecimalField(decimal_places=3, max_digits=12)),
                ('estado_ped', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('id_clien_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id_abono', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_abono', models.DateField(auto_now_add=True)),
                ('monto_abono', models.BigIntegerField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('id_pedido_fk_abono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Det_mov_matp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.movimiento_matp')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Variacion',
            fields=[
                ('id_var', models.AutoField(primary_key=True, serialize=False)),
                ('talla_var', models.CharField(max_length=50)),
                ('cant_soli', models.IntegerField()),
                ('color_var', models.CharField(max_length=100)),
                ('mat_var', models.CharField(max_length=200)),
                ('costo_var', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_estam_fk_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.estampado')),
            ],
        ),
        migrations.CreateModel(
            name='Det_valor',
            fields=[
                ('id_det_valor', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('talla', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('tipo_pedido', models.CharField(max_length=200)),
                ('id_ped_fk_detval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pedido')),
                ('id_prod_fk_detval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
                ('id_var_fk_detval', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.variacion')),
            ],
        ),
    ]
