# Generated by Django 4.2 on 2026-03-25 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_id_estam_estampado_id_estamp_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='det_mov_matp',
            name='materia_prima',
            field=models.ForeignKey(db_column='id_movi_mtp_fk_id_produc_id', on_delete=django.db.models.deletion.CASCADE, to='inventario.movimiento_matp'),
        ),
        migrations.AlterModelTable(
            name='det_mov_matp',
            table='ventas_det_mov_matp',
        ),
    ]
