# Generated by Django 4.2 on 2026-03-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_det_mov_matp_materia_prima_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='det_mov_matp',
            options={'managed': True},
        ),
    ]
