# Generated by Django 4.2 on 2026-04-24 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_det_mov_matp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='det_valor',
            name='id_personalizacion_3d',
        ),
    ]
