# Generated by Django 4.2 on 2026-04-24 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
        ('ventas', '0003_remove_det_valor_id_personalizacion_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='det_valor',
            name='id_personalizacion_3d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.pedidopersonalizado'),
        ),
    ]
