# Generated by Django 4.2 on 2026-04-24 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
        ('ventas', '0004_det_valor_id_personalizacion_3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacion',
            name='id_estam_fk_var',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.estampado'),
        ),
    ]
