# Generated by Django 4.2 on 2026-05-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nom_rol', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('id_rol_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_emple', models.AutoField(primary_key=True, serialize=False)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='empleados/')),
                ('hash_foto', models.CharField(blank=True, max_length=64, null=True)),
                ('nom_emple', models.CharField(max_length=50)),
                ('tel_emple', models.CharField(max_length=20)),
                ('correo_emple', models.CharField(max_length=100)),
                ('dir_emple', models.CharField(max_length=100)),
                ('rh_emple', models.CharField(max_length=20)),
                ('fecha_naci_emple', models.DateField()),
                ('tipo_ident', models.CharField(max_length=100)),
                ('num_ident', models.CharField(max_length=30)),
                ('fecha_ing_emple', models.DateField()),
                ('salari_emple', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_emple', models.CharField(max_length=50)),
                ('id_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_clien', models.AutoField(primary_key=True, serialize=False)),
                ('nom_clien', models.CharField(max_length=50)),
                ('dir_clien', models.CharField(max_length=100)),
                ('tel_clien', models.CharField(max_length=20)),
                ('correo_clien', models.CharField(max_length=100)),
                ('id_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
