# Generated by Django 4.2 on 2026-04-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='hash_foto',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
