# Generated by Django 6.0.3 on 2026-03-27 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estampado',
            fields=[
                ('id_estam', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estam', models.CharField(max_length=100)),
                ('link_estam', models.CharField(max_length=500)),
                ('costo_adi', models.FloatField()),
                ('tipo_estam', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_prove', models.AutoField(primary_key=True, serialize=False)),
                ('nom_provee', models.CharField(max_length=100)),
                ('fech_ingre', models.DateField()),
                ('num_tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento_matp',
            fields=[
                ('id_movi_mtp', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movi_mtp', models.CharField(max_length=100)),
                ('talla_movi_mtp', models.CharField(max_length=50)),
                ('color_movi_mtp', models.CharField(max_length=100)),
                ('fecha_movi_mtp', models.DateField()),
                ('stock_movi_mtp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_estam_fk_invent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.estampado')),
                ('id_proveedor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedor')),
            ],
        ),
    ]
