# Generated by Django 4.2 on 2026-03-10 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id_abono', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_abono', models.DateField()),
                ('monto_abono', models.BigIntegerField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('estado_abono', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_produc', models.AutoField(primary_key=True, serialize=False)),
                ('link_produc', models.CharField(max_length=500)),
                ('nom_produc', models.CharField(max_length=50)),
                ('desc_produc', models.CharField(max_length=200)),
                ('categoria_produc', models.CharField(max_length=50)),
                ('estado_produc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Variacion',
            fields=[
                ('id_var', models.AutoField(primary_key=True, serialize=False)),
                ('talla_var', models.CharField(max_length=50)),
                ('cant_soli', models.IntegerField()),
                ('color_var', models.CharField(max_length=100)),
                ('mat_var', models.CharField(max_length=200)),
                ('costo_var', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_estam_fk_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.estampado')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ped', models.CharField(max_length=100)),
                ('talla_ped', models.CharField(max_length=50)),
                ('color_ped', models.CharField(max_length=50)),
                ('categoria_ped', models.CharField(max_length=50)),
                ('material_ped', models.CharField(max_length=100)),
                ('cant_ped', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc_ped', models.CharField(max_length=200)),
                ('fecha_ped', models.DateField()),
                ('subtotal_ped', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_ped', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_ped', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('id_abono_fk_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.abono')),
                ('id_clien_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Det_valor',
            fields=[
                ('id_det_valor', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_pedido', models.CharField(max_length=200)),
                ('id_abono_fk_detval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.abono')),
                ('id_prod_fk_detval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
                ('id_var_fk_detval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.variacion')),
            ],
        ),
    ]
